version: 2
updates:
- package-ecosystem: bundler
  directory: "/"
  schedule:
    interval: daily
    timezone: Europe/London
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: nokogiri
    versions:
    - 1.11.1
    - 1.11.2
  - dependency-name: fog-aws
    versions:
    - 3.8.0
    - 3.9.0
  - dependency-name: puma
    versions:
    - 5.2.0
    - 5.2.1
